import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import Navbar from "@/components/NavBar";
import ContactFooter from "@/components/ContactFooter";

import { Inter } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth bg-slate-200 h-full">
      <body
        className={`bg-slate-200 antialiased min-h-screen flex flex-col ${inter.className}`}
      >
        {/* Header */}
        <Navbar />

        {/* Page content always grows */}
        <main className="flex-1">{children}</main>

        {/* Footer always at bottom */}
        <ContactFooter />
      </body>
    </html>
  );
}
